language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

script: "mvn install"

notifications:
  email:
    recipients:
      - binaek89@gmail.com
    on_failure: change
    on_success: change
